optparamc -g"BERMCCENTRE" -omixor -tbool   -n0         -pFtlOptUseBreaks            -l "Use Breaks"
optparamc -g"BERMCCENTRE" -omixor -tint    -n10        -pFtlOptTakenBreakPercentage -l ""
optparamc -g"BERMCCENTRE" -omixor -tint    -n15        -pFtlOptBreakLength1         -l "1st. Break: Length (min)"
optparamc -g"BERMCCENTRE" -omixor -tint    -n60        -pFtlOptBreakStart1          -l "1st. Break: Break Start within (min)"
optparamc -g"BERMCCENTRE" -omixor -tint    -n180       -pFtlOptBreakEnd1            -l "1st. Break: End within (min)"
optparamc -g"BERMCCENTRE" -omixor -tstring -sAllowed   -pFtlOptBreakType1           -l ""
optparamc -g"BERMCCENTRE" -omixor -tint    -n30        -pFtlOptBreakLength2         -l "2nd. Break: Length (min)"
optparamc -g"BERMCCENTRE" -omixor -tint    -n180       -pFtlOptBreakStart2          -l "2nd. Break: Break Start within (min)"
optparamc -g"BERMCCENTRE" -omixor -tint    -n360       -pFtlOptBreakEnd2            -l "2nd. Break: End within (min)"
optparamc -g"BERMCCENTRE" -omixor -tstring -sMandatory -pFtlOptBreakType2           -l ""
optparamc -g"BERMCCENTRE" -omixor -tint    -n15        -pFtlOptBreakLength3         -l "3rd. Break: Length (min)"
optparamc -g"BERMCCENTRE" -omixor -tint    -n360       -pFtlOptBreakStart3          -l "3rd. Break: Break Start within (min)"
optparamc -g"BERMCCENTRE" -omixor -tint    -n540       -pFtlOptBreakEnd3            -l "3rd. Break: End within (min)"
optparamc -g"BERMCCENTRE" -omixor -tstring -sPreferred -pFtlOptBreakType3           -l ""
optparamc -g"BERMCCENTRE" -omixor -tint    -n0         -pFtlOptBreakLength4         -l ""
optparamc -g"BERMCCENTRE" -omixor -tint    -n0         -pFtlOptBreakStart4          -l ""
optparamc -g"BERMCCENTRE" -omixor -tint    -n0         -pFtlOptBreakEnd4            -l ""
optparamc -g"BERMCCENTRE" -omixor -tstring -sDone      -pFtlOptBreakType4           -l ""

optparamc -g"BERMCNORTH" -omixor -tbool   -n0         -pFtlOptUseBreaks            -l "Use Breaks"
optparamc -g"BERMCNORTH" -omixor -tint    -n10        -pFtlOptTakenBreakPercentage -l ""
optparamc -g"BERMCNORTH" -omixor -tint    -n15        -pFtlOptBreakLength1         -l "1st. Break: Length (min)"
optparamc -g"BERMCNORTH" -omixor -tint    -n60        -pFtlOptBreakStart1          -l "1st. Break: Break Start within (min)"
optparamc -g"BERMCNORTH" -omixor -tint    -n180       -pFtlOptBreakEnd1            -l "1st. Break: End within (min)"
optparamc -g"BERMCNORTH" -omixor -tstring -sAllowed   -pFtlOptBreakType1           -l ""
optparamc -g"BERMCNORTH" -omixor -tint    -n30        -pFtlOptBreakLength2         -l "2nd. Break: Length (min)"
optparamc -g"BERMCNORTH" -omixor -tint    -n180       -pFtlOptBreakStart2          -l "2nd. Break: Break Start within (min)"
optparamc -g"BERMCNORTH" -omixor -tint    -n360       -pFtlOptBreakEnd2            -l "2nd. Break: End within (min)"
optparamc -g"BERMCNORTH" -omixor -tstring -sMandatory -pFtlOptBreakType2           -l ""
optparamc -g"BERMCNORTH" -omixor -tint    -n15        -pFtlOptBreakLength3         -l "3rd. Break: Length (min)"
optparamc -g"BERMCNORTH" -omixor -tint    -n360       -pFtlOptBreakStart3          -l "3rd. Break: Break Start within (min)"
optparamc -g"BERMCNORTH" -omixor -tint    -n540       -pFtlOptBreakEnd3            -l "3rd. Break: End within (min)"
optparamc -g"BERMCNORTH" -omixor -tstring -sPreferred -pFtlOptBreakType3           -l ""
optparamc -g"BERMCNORTH" -omixor -tint    -n0         -pFtlOptBreakLength4         -l ""
optparamc -g"BERMCNORTH" -omixor -tint    -n0         -pFtlOptBreakStart4          -l ""
optparamc -g"BERMCNORTH" -omixor -tint    -n0         -pFtlOptBreakEnd4            -l ""
optparamc -g"BERMCNORTH" -omixor -tstring -sDone      -pFtlOptBreakType4           -l ""

optparamc -g"BERMCSOUTH" -omixor -tbool   -n0         -pFtlOptUseBreaks            -l "Use Breaks"
optparamc -g"BERMCSOUTH" -omixor -tint    -n10        -pFtlOptTakenBreakPercentage -l ""
optparamc -g"BERMCSOUTH" -omixor -tint    -n15        -pFtlOptBreakLength1         -l "1st. Break: Length (min)"
optparamc -g"BERMCSOUTH" -omixor -tint    -n60        -pFtlOptBreakStart1          -l "1st. Break: Break Start within (min)"
optparamc -g"BERMCSOUTH" -omixor -tint    -n180       -pFtlOptBreakEnd1            -l "1st. Break: End within (min)"
optparamc -g"BERMCSOUTH" -omixor -tstring -sAllowed   -pFtlOptBreakType1           -l ""
optparamc -g"BERMCSOUTH" -omixor -tint    -n30        -pFtlOptBreakLength2         -l "2nd. Break: Length (min)"
optparamc -g"BERMCSOUTH" -omixor -tint    -n180       -pFtlOptBreakStart2          -l "2nd. Break: Break Start within (min)"
optparamc -g"BERMCSOUTH" -omixor -tint    -n360       -pFtlOptBreakEnd2            -l "2nd. Break: End within (min)"
optparamc -g"BERMCSOUTH" -omixor -tstring -sMandatory -pFtlOptBreakType2           -l ""
optparamc -g"BERMCSOUTH" -omixor -tint    -n15        -pFtlOptBreakLength3         -l "3rd. Break: Length (min)"
optparamc -g"BERMCSOUTH" -omixor -tint    -n360       -pFtlOptBreakStart3          -l "3rd. Break: Break Start within (min)"
optparamc -g"BERMCSOUTH" -omixor -tint    -n540       -pFtlOptBreakEnd3            -l "3rd. Break: End within (min)"
optparamc -g"BERMCSOUTH" -omixor -tstring -sPreferred -pFtlOptBreakType3           -l ""
optparamc -g"BERMCSOUTH" -omixor -tint    -n0         -pFtlOptBreakLength4         -l ""
optparamc -g"BERMCSOUTH" -omixor -tint    -n0         -pFtlOptBreakStart4          -l ""
optparamc -g"BERMCSOUTH" -omixor -tint    -n0         -pFtlOptBreakEnd4            -l ""
optparamc -g"BERMCSOUTH" -omixor -tstring -sDone      -pFtlOptBreakType4           -l ""

optparamc -g"BERMCWEST" -omixor -tbool   -n0         -pFtlOptUseBreaks            -l "Use Breaks"
optparamc -g"BERMCWEST" -omixor -tint    -n10        -pFtlOptTakenBreakPercentage -l ""
optparamc -g"BERMCWEST" -omixor -tint    -n15        -pFtlOptBreakLength1         -l "1st. Break: Length (min)"
optparamc -g"BERMCWEST" -omixor -tint    -n60        -pFtlOptBreakStart1          -l "1st. Break: Break Start within (min)"
optparamc -g"BERMCWEST" -omixor -tint    -n180       -pFtlOptBreakEnd1            -l "1st. Break: End within (min)"
optparamc -g"BERMCWEST" -omixor -tstring -sAllowed   -pFtlOptBreakType1           -l ""
optparamc -g"BERMCWEST" -omixor -tint    -n30        -pFtlOptBreakLength2         -l "2nd. Break: Length (min)"
optparamc -g"BERMCWEST" -omixor -tint    -n180       -pFtlOptBreakStart2          -l "2nd. Break: Break Start within (min)"
optparamc -g"BERMCWEST" -omixor -tint    -n360       -pFtlOptBreakEnd2            -l "2nd. Break: End within (min)"
optparamc -g"BERMCWEST" -omixor -tstring -sMandatory -pFtlOptBreakType2           -l ""
optparamc -g"BERMCWEST" -omixor -tint    -n15        -pFtlOptBreakLength3         -l "3rd. Break: Length (min)"
optparamc -g"BERMCWEST" -omixor -tint    -n360       -pFtlOptBreakStart3          -l "3rd. Break: Break Start within (min)"
optparamc -g"BERMCWEST" -omixor -tint    -n540       -pFtlOptBreakEnd3            -l "3rd. Break: End within (min)"
optparamc -g"BERMCWEST" -omixor -tstring -sPreferred -pFtlOptBreakType3           -l ""
optparamc -g"BERMCWEST" -omixor -tint    -n0         -pFtlOptBreakLength4         -l ""
optparamc -g"BERMCWEST" -omixor -tint    -n0         -pFtlOptBreakStart4          -l ""
optparamc -g"BERMCWEST" -omixor -tint    -n0         -pFtlOptBreakEnd4            -l ""
optparamc -g"BERMCWEST" -omixor -tstring -sDone      -pFtlOptBreakType4           -l ""

optparamc -g"NLRMC" -omixor -tbool   -n0         -pFtlOptUseBreaks            -l "Use Breaks"
optparamc -g"NLRMC" -omixor -tint    -n10        -pFtlOptTakenBreakPercentage -l ""
optparamc -g"NLRMC" -omixor -tint    -n15        -pFtlOptBreakLength1         -l "1st. Break: Length (min)"
optparamc -g"NLRMC" -omixor -tint    -n60        -pFtlOptBreakStart1          -l "1st. Break: Break Start within (min)"
optparamc -g"NLRMC" -omixor -tint    -n180       -pFtlOptBreakEnd1            -l "1st. Break: End within (min)"
optparamc -g"NLRMC" -omixor -tstring -sAllowed   -pFtlOptBreakType1           -l ""
optparamc -g"NLRMC" -omixor -tint    -n30        -pFtlOptBreakLength2         -l "2nd. Break: Length (min)"
optparamc -g"NLRMC" -omixor -tint    -n180       -pFtlOptBreakStart2          -l "2nd. Break: Break Start within (min)"
optparamc -g"NLRMC" -omixor -tint    -n360       -pFtlOptBreakEnd2            -l "2nd. Break: End within (min)"
optparamc -g"NLRMC" -omixor -tstring -sMandatory -pFtlOptBreakType2           -l ""
optparamc -g"NLRMC" -omixor -tint    -n15        -pFtlOptBreakLength3         -l "3rd. Break: Length (min)"
optparamc -g"NLRMC" -omixor -tint    -n360       -pFtlOptBreakStart3          -l "3rd. Break: Break Start within (min)"
optparamc -g"NLRMC" -omixor -tint    -n540       -pFtlOptBreakEnd3            -l "3rd. Break: End within (min)"
optparamc -g"NLRMC" -omixor -tstring -sPreferred -pFtlOptBreakType3           -l ""
optparamc -g"NLRMC" -omixor -tint    -n0         -pFtlOptBreakLength4         -l ""
optparamc -g"NLRMC" -omixor -tint    -n0         -pFtlOptBreakStart4          -l ""
optparamc -g"NLRMC" -omixor -tint    -n0         -pFtlOptBreakEnd4            -l ""
optparamc -g"NLRMC" -omixor -tstring -sDone      -pFtlOptBreakType4           -l ""
